//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaArticulosCredito.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public Carrito(int codigoUsuario, int codigoInventario, int cantidad)
        {
            this.codigoInventario = codigoInventario;
            this.codigoUsuario = codigoUsuario;
            this.cantidad = cantidad;
        }

        public Carrito()
        {

        }

        public int correlativo { get; set; }
        public Nullable<int> codigoUsuario { get; set; }
        public Nullable<int> codigoInventario { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual Inventario Inventario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
