//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaArticulosCredito.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelativoFactura
    {
        public CorrelativoFactura(string codigoFactura)
        {
            this.codigoFactura = codigoFactura;
        }

        public CorrelativoFactura()
        {

        }

        public int correlativo { get; set; }
        public string codigoFactura { get; set; }
    }
}
