//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaArticulosCredito.DBEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentaArticulosCreditoEntities : DbContext
    {
        public VentaArticulosCreditoEntities()
            : base("name=VentaArticulosCreditoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Carrito> Carrito { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CorrelativoFactura> CorrelativoFactura { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Descuento_Articulo> Descuento_Articulo { get; set; }
        public virtual DbSet<DetalleFactura> DetalleFactura { get; set; }
        public virtual DbSet<Direccion_Usuario> Direccion_Usuario { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Imagen_Articulo> Imagen_Articulo { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SubCategoria> SubCategoria { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
