//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaArticulosCredito.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public DetalleFactura(int posicion, int codigoFactura, decimal precio, int cantidad, int codigoArticulo)
        {
            this.posicion = posicion;
            this.codigoFactura = codigoFactura;
            this.precio = precio;
            this.cantidad = cantidad;
            this.codigoArticulo = codigoArticulo;
        }

        public DetalleFactura()
        {

        }

        public int posicion { get; set; }
        public int codigoFactura { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> codigoArticulo { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
