//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaArticulosCredito.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direccion_Usuario()
        {
            this.Factura = new HashSet<Factura>();
        }

        public Direccion_Usuario(int codigoUsuario, int telefono, string direccion, int codigoMunicipio, string nombre, string apellido)
        {
            this.codigoUsuario = codigoUsuario;
            this.telefono = telefono;
            this.direccion = direccion;
            this.codigoMunicipio = codigoMunicipio;
            this.nombre = nombre;
            this.apellido = apellido;
        }

        public int codigo { get; set; }
        public Nullable<int> codigoUsuario { get; set; }
        public Nullable<int> telefono { get; set; }
        public string direccion { get; set; }
        public Nullable<int> codigoMunicipio { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
