//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaArticulosCredito.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }

        public Factura(int codigo, DateTime fecha, int codigoUsuario, int estado, int direccionEntrega)
        {
            this.codigo = codigo;
            this.fecha = fecha;
            this.codigoUsuario = codigoUsuario;
            this.estado = estado;
            this.direccionEntrega = direccionEntrega;
        }

        public int codigo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> codigoUsuario { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> direccionEntrega { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual Direccion_Usuario Direccion_Usuario { get; set; }
    }
}
