//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaArticulosCredito.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen_Articulo
    {   
        public Imagen_Articulo()
        {

        }

        public Imagen_Articulo(int codigoArticulo)
        {
            this.codigoArticulo = codigoArticulo;
        }

        public int codigo { get; set; }
        public Nullable<int> codigoArticulo { get; set; }
        public string imagen { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
